setwd("C:\\Users\\DELL\\Downloads\\AI_Omics_Internship_2025")
dir.create("Module_I")
getwd()
setwd("C:\\Users\\DELL\\Downloads\\AI_Omics_Internship_2025\\Module_I")
dir.create("data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
dir.create("plots")
data <- read.csv(file.choose())
str(data)
data$age<-as.numeric(data$age)
class(age)
str(data)
data$smoking_status <- ifelse(data$smoker =="Yes",1,0)
class(data)
class(smoking_status)
str(data)
write.csv(data, file="clean_data/patient_info_clean")
